<x-app-layout>
<div class="cds container py-4">

    <livewire:applications.show-call :id="$id" />

    <!-- APPLICATIONS TABLE (static, with dummy filter/pagination shown as static UI but fully styled) -->
    <div class="cds-card">
        <div class="cds-card-header px-4 pt-4 pb-0 flex-column align-items-stretch gap-3">
            <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-3">
                <div><div class="d-flex align-items-center gap-2 mb-1"><div class="cds-icon-sm"><i class="bi bi-file-earmark-person-fill"></i></div><h5 class="fw-bold mb-0">Applications</h5></div><p class="small text-muted mb-0">All submissions received for this call</p></div>
                <div class="d-flex gap-2 flex-wrap"><button class="btn cds-btn-ghost btn-sm" id="exportAppsBtn"><i class="bi bi-download me-1"></i>Export</button><button class="btn cds-btn-primary btn-sm opacity-40 pe-none" disabled><i class="bi bi-check2-square me-1"></i>Bulk Action <span class="cds-count-badge ms-1">0</span></button></div>
            </div>
            <div class="cds-tab-row"><button class="cds-tab-btn cds-tab-active">All <span class="cds-tab-count">10</span></button><button class="cds-tab-btn">Pending <span class="cds-tab-count">2</span></button><button class="cds-tab-btn">In Review <span class="cds-tab-count">2</span></button><button class="cds-tab-btn">Eligible <span class="cds-tab-count">3</span></button><button class="cds-tab-btn">Shortlisted <span class="cds-tab-count">2</span></button><button class="cds-tab-btn">Rejected <span class="cds-tab-count">1</span></button></div>
        </div>
        <div class="cds-filter-bar"><div class="row g-2 align-items-center"><div class="col-12 col-md-4"><div class="cds-search-wrap"><i class="bi bi-search cds-search-icon"></i><input type="text" class="cds-search-input" placeholder="Search enterprise, owner, ID…"></div></div><div class="col-6 col-md-2"><select class="cds-select"><option value="">All Sectors</option><option>Agriculture</option><option>Technology</option><option>Textile</option><option>Manufacturing</option><option>Food & Beverage</option></select></div><div class="col-6 col-md-2"><select class="cds-select"><option value="">All Districts</option><option>Maseru</option><option>Leribe</option><option>Berea</option><option>Mafeteng</option><option>Mohale's Hoek</option></select></div><div class="col-6 col-md-2"><select class="cds-select"><option value="">All Stages</option><option>Idea</option><option>Non-Registered Startup</option><option>Registered Startup</option><option>Formally Registered</option></select></div><div class="col-6 col-md-2"><button class="btn cds-btn-ghost btn-sm w-100"><i class="bi bi-x-circle me-1"></i>Reset</button></div></div></div>
        <div class="table-responsive">
            <table class="table cds-table align-middle mb-0">
                <thead><tr><th class="px-4" style="width:42px;"><input class="cds-check" type="checkbox"></th><th style="min-width:210px;">Enterprise</th><th>Owner</th><th>Sector</th><th>District</th><th>Stage</th><th class="text-center">Docs</th><th class="text-center">Score</th><th>PDO</th><th>Submitted</th><th>Status</th><th class="text-center pe-4">Actions</th></tr></thead>
                <tbody>
                    <tr><td class="px-4"><input class="cds-check" type="checkbox"></td><td class="py-3"><div class="d-flex align-items-center gap-2"><div class="cds-av av-green"><span>LM</span></div><div><div class="fw-semibold text-dark small">MoroAgri Basotho</div><div class="cds-sub-text">APP-001</div></div></div></td><td><div class="small">Limpho Mokoena</div><div class="cds-sub-text">+266 5823 1234</div></td><td><span class="cds-sector-tag cds-sector-tag-sm">Agriculture</span></td><td class="small">Maseru</td><td><span class="cds-stage-tag">Registered Startup</span></td><td class="text-center"><div class="d-flex align-items-center justify-content-center gap-1"><div class="cds-doc doc-ok"></div><div class="cds-doc doc-ok"></div><div class="cds-doc doc-ok"></div><div class="cds-doc doc-ok"></div></div><div class="cds-sub-text mt-1">4/4</div></td><td class="text-center"><span class="cds-score fw-bold text-success">78%</span></td><td><div class="d-flex gap-1"><span class="cds-pdo-tag pdo-w">W</span><span class="cds-pdo-tag pdo-y">Y</span><span class="cds-pdo-tag pdo-off">R</span></div></td><td class="small">01 Feb 2025</td><td><span class="cds-app-status st-eligible">Eligible</span></td><td class="text-center pe-4"><div class="d-flex justify-content-center gap-1"><button class="cds-action-btn"><i class="bi bi-eye"></i></button><div class="dropdown"><button class="cds-action-btn" data-bs-toggle="dropdown"><i class="bi bi-three-dots-vertical"></i></button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="#">Mark Eligible</a></li><li><a class="dropdown-item" href="#">Move to Review</a></li><li><a class="dropdown-item" href="#">Shortlist</a></li><li><hr class="dropdown-divider"></li><li><a class="dropdown-item text-danger" href="#">Reject</a></li></ul></div></div></td></tr>
                    <tr><td class="px-4"><input class="cds-check" type="checkbox"></td><td><div class="d-flex align-items-center gap-2"><div class="cds-av av-pink"><span>TR</span></div><div><div class="fw-semibold text-dark small">Lesotho Stitch Co.</div><div class="cds-sub-text">APP-002</div></div></div></td><td><div class="small">Thabo Ramokhele</div><div class="cds-sub-text">+266 5861 4321</div></td><td><span class="cds-sector-tag cds-sector-tag-sm">Textile</span></td><td class="small">Leribe</td><td><span class="cds-stage-tag">Formally Registered</span></td><td class="text-center"><div class="d-flex justify-content-center gap-1"><div class="cds-doc doc-ok"></div><div class="cds-doc doc-ok"></div><div class="cds-doc doc-ok"></div><div class="cds-doc doc-nil"></div></div><div class="cds-sub-text mt-1">3/4</div></td><td class="text-center"><span class="cds-score fw-bold text-warning">65%</span></td><td><div class="d-flex gap-1"><span class="cds-pdo-tag pdo-off">W</span><span class="cds-pdo-tag pdo-off">Y</span><span class="cds-pdo-tag pdo-off">R</span></div></td><td class="small">02 Feb 2025</td><td><span class="cds-app-status st-eligible">Eligible</span></td><td class="text-center"><div class="d-flex justify-content-center gap-1"><button class="cds-action-btn"><i class="bi bi-eye"></i></button><div class="dropdown"><button class="cds-action-btn" data-bs-toggle="dropdown"><i class="bi bi-three-dots-vertical"></i></button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="#">Mark Eligible</a></li><li><a class="dropdown-item" href="#">Move to Review</a></li><li><a class="dropdown-item" href="#">Shortlist</a></li><li><hr class="dropdown-divider"></li><li><a class="dropdown-item text-danger" href="#">Reject</a></li></ul></div></div></td></tr>
                    <tr><td class="px-4"><input class="cds-check" type="checkbox"></td><td><div class="d-flex align-items-center gap-2"><div class="cds-av av-blue"><span>PN</span></div><div><div class="fw-semibold text-dark small">TechForward LS</div><div class="cds-sub-text">APP-003</div></div></div></td><td><div class="small">Palesa Nthako</div><div class="cds-sub-text">+266 5834 9876</div></td><td><span class="cds-sector-tag cds-sector-tag-sm">Technology</span></td><td class="small">Maseru</td><td><span class="cds-stage-tag">Non-Registered Startup</span></td><td class="text-center"><div class="d-flex justify-content-center gap-1"><div class="cds-doc doc-no"></div><div class="cds-doc doc-no"></div><div class="cds-doc doc-ok"></div><div class="cds-doc doc-ok"></div></div><div class="cds-sub-text mt-1">2/4</div></td><td class="text-center"><span class="text-muted">—</span></td><td><div class="d-flex gap-1"><span class="cds-pdo-tag pdo-w">W</span><span class="cds-pdo-tag pdo-y">Y</span><span class="cds-pdo-tag pdo-off">R</span></div></td><td class="small">03 Feb 2025</td><td><span class="cds-app-status st-in-review">In Review</span></td><td class="text-center"><div class="d-flex justify-content-center gap-1"><button class="cds-action-btn"><i class="bi bi-eye"></i></button><div class="dropdown"><button class="cds-action-btn" data-bs-toggle="dropdown"><i class="bi bi-three-dots-vertical"></i></button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="#">Mark Eligible</a></li><li><a class="dropdown-item" href="#">Move to Review</a></li><li><a class="dropdown-item" href="#">Shortlist</a></li><li><hr class="dropdown-divider"></li><li><a class="dropdown-item text-danger" href="#">Reject</a></li></ul></div></div></td></tr>
                    <tr><td class="px-4"><input class="cds-check" type="checkbox"></td><td><div class="d-flex align-items-center gap-2"><div class="cds-av av-teal"><span>RM</span></div><div><div class="fw-semibold text-dark small">Khomo Foods Ltd</div><div class="cds-sub-text">APP-004</div></div></div></td><td><div class="small">Retselisitsoe M.</div><div class="cds-sub-text">+266 5878 1122</div></td><td><span class="cds-sector-tag cds-sector-tag-sm">Food & Beverage</span></td><td class="small">Berea</td><td><span class="cds-stage-tag">Formally Registered</span></td><td class="text-center"><div class="d-flex justify-content-center gap-1"><div class="cds-doc doc-ok"></div><div class="cds-doc doc-ok"></div><div class="cds-doc doc-ok"></div><div class="cds-doc doc-ok"></div></div><div class="cds-sub-text mt-1">4/4</div></td><td class="text-center"><span class="text-muted">—</span></td><td><div class="d-flex gap-1"><span class="cds-pdo-tag pdo-off">W</span><span class="cds-pdo-tag pdo-off">Y</span><span class="cds-pdo-tag pdo-off">R</span></div></td><td class="small">03 Feb 2025</td><td><span class="cds-app-status st-rejected">Rejected</span></td><td class="text-center"><div class="d-flex justify-content-center gap-1"><button class="cds-action-btn"><i class="bi bi-eye"></i></button><div class="dropdown"><button class="cds-action-btn" data-bs-toggle="dropdown"><i class="bi bi-three-dots-vertical"></i></button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="#">Mark Eligible</a></li><li><a class="dropdown-item" href="#">Move to Review</a></li><li><a class="dropdown-item" href="#">Shortlist</a></li><li><hr class="dropdown-divider"></li><li><a class="dropdown-item text-danger" href="#">Reject</a></li></ul></div></div></td></tr>
                    <tr><td class="px-4"><input class="cds-check" type="checkbox"></td><td><div class="d-flex align-items-center gap-2"><div class="cds-av av-pink"><span>NS</span></div><div><div class="fw-semibold text-dark small">Naledi Weave Studio</div><div class="cds-sub-text">APP-005</div></div></div></td><td><div class="small">Naledi Sello</div><div class="cds-sub-text">+266 5812 5566</div></td><td><span class="cds-sector-tag cds-sector-tag-sm">Textile</span></td><td class="small">Mafeteng</td><td><span class="cds-stage-tag">Formally Registered</span></td><td class="text-center"><div class="d-flex justify-content-center gap-1"><div class="cds-doc doc-ok"></div><div class="cds-doc doc-ok"></div><div class="cds-doc doc-ok"></div><div class="cds-doc doc-ok"></div></div><div class="cds-sub-text mt-1">4/4</div></td><td class="text-center"><span class="cds-score fw-bold text-success">82%</span></td><td><div class="d-flex gap-1"><span class="cds-pdo-tag pdo-w">W</span><span class="cds-pdo-tag pdo-off">Y</span><span class="cds-pdo-tag pdo-r">R</span></div></td><td class="small">04 Feb 2025</td><td><span class="cds-app-status st-shortlisted">Shortlisted</span></td><td class="text-center"><div class="d-flex justify-content-center gap-1"><button class="cds-action-btn"><i class="bi bi-eye"></i></button><div class="dropdown"><button class="cds-action-btn" data-bs-toggle="dropdown"><i class="bi bi-three-dots-vertical"></i></button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="#">Mark Eligible</a></li><li><a class="dropdown-item" href="#">Move to Review</a></li><li><a class="dropdown-item" href="#">Shortlist</a></li><li><hr class="dropdown-divider"></li><li><a class="dropdown-item text-danger" href="#">Reject</a></li></ul></div></div></td></tr>
                </tbody>
            </table>
        </div>
        <div class="cds-pagination-bar"><small class="text-muted">Showing 1–5 of 10</small><div class="d-flex align-items-center gap-2"><select class="cds-select" style="width:auto;"><option value="10">10 / page</option><option value="25">25 / page</option><option value="50">50 / page</option></select><div class="d-flex gap-1"><button class="cds-page-btn" disabled><i class="bi bi-chevron-left"></i></button><button class="cds-page-btn cds-page-active">1</button><button class="cds-page-btn">2</button><button class="cds-page-btn"><i class="bi bi-chevron-right"></i></button></div></div></div>
    </div>
</div>

<livewire:notify />
<livewire:applications.modals.calls-for-application />
</x-app-layout> 